export const definitions = {
  data: [],
  boxes: [],
  containers: [],
  containerBoxes: [],
  value: [],
  containerData: [],
  titles: ['Pallets', 'Selected Pallets'],
  canvas: [],
  context: [],
  container: '',
  containerCopy: [],
  shipping: '',
  type: null,
  shippingTitles: ['By Sea', 'By Truck', 'By Plane', 'Articulated vehicle'],
  filename: '',
  filenames: [],
  contextArray: [],
  fileList: [],
  canvases: [],
  selectedOrder: 0,
  editType: 'Rotate',
  containerRotatedBoxes: [],
  editingScale: 'FillContainer',
  numberOfCont: 0,
  loadingGetBoxesAndCont: false,
  EditQueue: 0,
  editFinished: false,
  filteredObject: {},
  firstForEdit: {},
  secondForEdit: {},
  containerSwapedBoxes: [],
  containerForEdit: null,
  globalCanvasEdit: null
}
